name: Lint Code Base

on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
